### ISSUE TITLE
❤️阶段一作业合集❤️ 

### ISSUE THREAD

**Issue by liangyepianzhou** [liangyepianzhou/JAVA01#1]
将你的阶段一的作业提交到此issue下

**Comment by ChenNoCode** [comment]
姓名：陈泉屹
导师：邓娇娇
https://github.com/2369917438/JAVA01
（还未完成，在慢慢肝了）

**Comment by simon471j** [comment]
姓名：江鸿磊
导师：邓嘉文
https://github.com/simon471j/JAVA01

**Comment by wksports** [comment]
姓名：王治凯
导师：孟祥迎
https://github.com/wksports/JAVA01
持续更新

**Comment by rushyhf** [comment]
姓名 杨海峰
导师 谭世鑫
作业链接 https://github.com/rushyhf/JAVA01

**Comment by xuelu55** [comment]
姓名：薛路
导师：孟祥迎
作业链接：https://github.com/xuegao-xu/JAVA01

**Comment by 2372607196** [comment]
姓名：王豪
导师：孟祥迎
作业链接：https://github.com/2372607196/JAVA01

**Comment by hjx424** [comment]
姓名：侯嘉旋
导师：邓嘉文
作业链接：https://github.com/hjx424/JAVA01

**Comment by liangyepianzhou** [comment]
> 姓名：陈泉屹
> 导师：邓娇娇
> https://github.com/2369917438/JAVA01
> （还未完成，在慢慢肝了）

做完后请重新comment

**Comment by QinHaodong-end** [comment]
姓名：秦皓东
导师：邓嘉文
作业链接：https://blog.csdn.net/weixin_44625949?spm=1000.2115.3001.5343

**Comment by Self-reliance1110** [comment]
# 姓名 李烘
# 导师 邓娇娇
# 作业链接 https://github.com/Self-reliance1110/JAVA01

**Comment by L-XRay** [comment]
姓名：夏瑞
导师：王宇宁
作业链接：[https://github.com/L-XRay/JAVA01.git](url)
//更新ing，给我点时间

**Comment by L-XRay** [comment]
姓        名：夏    瑞
导        师：王宇宁
作业链接：https://github.com/L-XRay/JAVA01.git

**Comment by hiriki** [comment]
姓       名：夏        瑞
导       师：王  宇  宁
作业链接：https://github.com/L-XRay/JAVA01.git

//更新ing，给我点时间

**Comment by 02hc** [comment]
姓名： 黄琪超
导师 ：阙逍宇
作业链接：https://github.com/02hc/JAVA01

**Comment by liangyepianzhou** [comment]
> 姓名：王治凯
> 导师：孟祥迎
> https://github.com/wksports/JAVA01
> 持续更新

完成后请重新comment

**Comment by Jack-Lvv** [comment]
姓名：吕保辉
导师：孟祥迎
https://github.com/Jack-Lvv/JAVA01

**Comment by Ruxury-cloud** [comment]
#姓名 李洳旭
#导师 孟祥迎
#作业链接：https://github.com/Ruxury-cloud/refactored-spork.git

**Comment by 0525-del** [comment]
#姓名 甄鈞江
#导师 阙逍宇
#作业链接 https://github.com/0525-del/nmid-end-zhenjunjiang.git

**Comment by jimyao4** [comment]
#姓名 姚金明
#导师 阙逍宇
#作业链接 https://github.com/jimyao4/JAVA.git

**Comment by WWWOWhite** [comment]
#姓名 白恒阳
#导师 王宇宁
#作业链接 https://github.com/Ttinywhite/NIMD_work

**Comment by Xlhhshuai** [comment]
#姓名：刘恬吉
#导师：谭世鑫
#作业链接：https://github.com/Xlhhshuai/nmidwork.git

**Comment by Xlhhshuai** [comment]
#姓名:刘恬吉
#导师:谭世鑫
#作业链接:https://github.com/Xlhhshuai/nmidwork.git
持续更新
